name: Build, Package, and Release Python App

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g., v1.0.0)'
        required: true
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest  # Change to Windows for .exe build

    permissions:
      contents: write  # Needed for creating releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build binary with PyInstaller
        run: cmd /c "pyinstaller --onefile --name main.exe --add-data utils;utils --add-data processors;processors --add-data gui.py;. main.py"

      - name: Package application into ZIP
        run: |
          mkdir release
          copy dist\app.exe release\
          powershell Compress-Archive -Path release\* -DestinationPath release\app.zip

      - name: Determine tag name
        id: tag_name
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          files: release/app.zip
