name: Build and Package Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile main.py

      - name: Package application into ZIP
        run: |
          mkdir -p build_artifacts
          cp dist/main build_artifacts/
          cp -r utils build_artifacts/
          cp -r processors build_artifacts/
          cp gui.py build_artifacts/
          cd build_artifacts && zip -r app.zip . && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-binary
          path: build_artifacts/app.zip
